name: employee_attendance_app
description: Office Attendance - Employee attendance management with face recognition.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  
  # Camera and Image Processing
  camera: ^0.11.2
  image: ^4.1.3
  
  # ML Kit for Face Detection
  google_mlkit_face_detection: ^0.13.1
  
  # TensorFlow Lite for Face Recognition
  tflite_flutter: ^0.11.0
  
  # State Management
  provider: ^6.1.1
  
  # UI and Utilities
  path_provider: ^2.1.1
  path: ^1.8.3
  intl: ^0.20.2
  
  # Permissions
  permission_handler: ^12.0.1
  
  # Location Services
  geolocator: ^14.0.2
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
  
  # Add any fonts if needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/yo-removebg-preview.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/yo-removebg-preview.png"
    background_color: "#ffffff"
    theme_color: "#3F51B5"
  windows:
    generate: true
    image_path: "assets/images/yo-removebg-preview.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/yo-removebg-preview.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/yo-removebg-preview.png"
  android_12:
    color: "#FFFFFF"
    image: "assets/images/yo-removebg-preview.png"
  ios: true
  android: true
