// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrRY6-xLnWB7DJfaVBc2vd7Ewuf4XRZmI',
    appId: '1:56072423677:web:5808a2dd85593b8ff31694',
    messagingSenderId: '56072423677',
    projectId: 'employee-attendance-app-b8ad4',
    authDomain: 'employee-attendance-app-b8ad4.firebaseapp.com',
    storageBucket: 'employee-attendance-app-b8ad4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrRY6-xLnWB7DJfaVBc2vd7Ewuf4XRZmI',
    appId: '1:56072423677:android:b030a94c323d1146f31694',
    messagingSenderId: '56072423677',
    projectId: 'employee-attendance-app-b8ad4',
    storageBucket: 'employee-attendance-app-b8ad4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrRY6-xLnWB7DJfaVBc2vd7Ewuf4XRZmI',
    appId: '1:56072423677:ios:370daf3a52ba867cf31694',
    messagingSenderId: '56072423677',
    projectId: 'employee-attendance-app-b8ad4',
    storageBucket: 'employee-attendance-app-b8ad4.firebasestorage.app',
    iosBundleId: 'com.example.employeeAttendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrRY6-xLnWB7DJfaVBc2vd7Ewuf4XRZmI',
    appId: '1:56072423677:ios:370daf3a52ba867cf31694',
    messagingSenderId: '56072423677',
    projectId: 'employee-attendance-app-b8ad4',
    storageBucket: 'employee-attendance-app-b8ad4.firebasestorage.app',
    iosBundleId: 'com.example.employeeAttendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrRY6-xLnWB7DJfaVBc2vd7Ewuf4XRZmI',
    appId: '1:56072423677:web:5808a2dd85593b8ff31694',
    messagingSenderId: '56072423677',
    projectId: 'employee-attendance-app-b8ad4',
    authDomain: 'employee-attendance-app-b8ad4.firebaseapp.com',
    storageBucket: 'employee-attendance-app-b8ad4.firebasestorage.app',
  );
} 